services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./db-init:/db-init
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      echo 'Waiting for SQL Server to start...' && 
      sleep 20 &&
      until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1'; do 
        echo 'SQL Server is not ready yet. Retrying in 5 seconds...';
        sleep 5;
      done &&
      echo 'SQL Server is ready! Running init.sql...' &&
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -i /db-init/init.sql &&
      tail -f /dev/null"
    # healthcheck:
    #   test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 20s
      
  myapi:
    image: kingyuva/projectk-myapi:v1
    container_name: myapi
    environment:
      - ConnectionStrings__TodoDatabase=Server=sqlserver;Database=TodoDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    # depends_on:
    #   sqlserver:
    #     condition: service_healthy
  
  angular:
    image: kingyuva/projectk-angular:v1
    container_name: angular
    ports:
      - "4200:80"
    depends_on:
      - myapi
volumes:
  sqlserver_data:
